<?php
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountProxyInterface;
use Drupal\user\UserInterface;

/**
* Implements hook_help().
*/
function file_upload_help($route_name, RouteMatchInterface $route_match) {
    
  
      // Main module help for the block module.
      
        return '<p>' . t('COUCOU', [
          ':blocks' => \Drupal::url('block.admin_display'),
        ]) . '</p>';
  
     
  }

/**
* Implements hook_cron().
*/
  function file_upload_cron() {

    \Drupal::messenger()->addMessage('Upload cron.');
  }

  function file_upload_user_login(UserInterface $account) {
    // Fonction t().
    // Il existe 3 types de jetons indiquant comment on substitue les variables.
    // ! : le contenu de la variable est interprété.
    // @ : le contenu de la variable est échappé.
    // % : le contenu de la variable est échappé et la balise <em> est ajoutée.
    \Drupal::messenger()->addMessage(t('Welcome dear %name!',
                         ['%name' => $account->getAccountName()] 
                        
    ));
    \Drupal::database()->insert('file_upload_user_statistics')
        ->fields([
        'uid' => $account->id(),
        'action' => '1',
        'time' => REQUEST_TIME,
     ])
   ->execute();
  
   }


   
   
   function file_upload_user_logout(AccountProxyInterface $account) {
     \Drupal::messenger()->addMessage(t('Welcome dear %name!',
                         ['%name' => $account->getAccountName()] 
   ));
      \Drupal::database()->insert('file_upload_user_statistics')
   ->fields([
   'uid' => $account->id(),
   'action' => '0',
   'time' => REQUEST_TIME,
])
->execute();
   
  }
